# Generated by Django 2.2 on 2019-04-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('category', models.CharField(choices=[('ECO', 'Conference'), ('HIS', 'Workshops & Training'), ('BAK', 'College Fest'), ('GOV', 'Sports Event'), ('PSY', 'Entertainment Events')], max_length=3)),
                ('level', models.IntegerField(default=0)),
                ('userAtt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bsl.user')),
            ],
        ),
    ]
