# Generated by Django 2.2 on 2019-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionA',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionB',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionC',
            field=models.CharField(max_length=300),
        ),
    ]
