# Generated by Django 2.2 on 2019-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0002_auto_20190412_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optionD',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
