# Generated by Django 2.2 on 2019-04-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0003_question_optiond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='userAtt',
        ),
    ]
