# Generated by Django 2.2 on 2019-04-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0004_remove_question_useratt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
