# Generated by Django 2.2 on 2019-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0006_auto_20190412_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='Shivam', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='Gupta', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='Student', max_length=30),
            preserve_default=False,
        ),
    ]
