# Generated by Django 2.2 on 2019-04-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0007_auto_20190412_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('C', 'Correct'), ('W', 'Wrong')], max_length=1)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bsl.Question')),
                ('userAtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.user')),
            ],
        ),
    ]
