# Generated by Django 2.2 on 2019-04-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0009_auto_20190412_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='Lorem', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='question',
            name='ratingChange',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.IntegerField()),
                ('preSkill', models.IntegerField()),
                ('postSkill', models.IntegerField()),
                ('score', models.IntegerField()),
                ('confidenceLevel', models.IntegerField()),
                ('userV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.user')),
            ],
        ),
    ]
