# Generated by Django 2.2 on 2019-04-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0010_auto_20190412_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='confidenceLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
    ]
