# Generated by Django 2.2 on 2019-04-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0012_auto_20190412_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
    ]
