# Generated by Django 2.2 on 2019-04-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0013_auto_20190412_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='clicks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='confidenceLevel',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
    ]
