# Generated by Django 2.2 on 2019-04-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0016_auto_20190412_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_level_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
    ]
