# Generated by Django 2.2 on 2019-04-13 03:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0022_auto_20190413_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 3, 53, 5, 41107, tzinfo=utc)),
        ),
    ]
