# Generated by Django 2.2 on 2019-04-13 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0023_auto_20190413_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsl.Question'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='quizid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 5, 2, 21, 24090, tzinfo=utc)),
        ),
    ]
